language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

before_install:
  - cp README.md README.rst
  - pip install flake8

install:
  - pip install -e .

script:
  - bash scripts/test.sh
  - flake8 nanofilt/NanoFilt.py

notifications:
  email: false
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/4b1c45cea6826ce475c2
